export { apiBaseUrl, httpClient, request, ApiClientError } from './httpClient'
export type { ApiClientProblem } from './httpClient'
export { getOpenApiDocument } from './openApi'
export type { OpenApiDocument, OpenApiInfo, OpenApiTag } from './openApi'
export { getProductById, getProducts } from './catalog'
export type { ProductDetail, ProductListItem, StockStatus } from './catalog'
