package dev.hoangtuan.shopflow.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * OpenAPI configuration for the Shopflow backend.
 * <p>
 * Swagger UI is generated by Springdoc at {@code /swagger-ui.html}
 * and the OpenAPI spec is available at {@code /v3/api-docs}.
 */
@Configuration
public class OpenApiConfig {

    @Value("${spring.application.name:shopflow-backend}")
    private String applicationName;

    @Value("${shopflow.openapi.version:0.0.1-SNAPSHOT}")
    private String apiVersion;

    @Bean
    public OpenAPI shopflowOpenAPI() {
        return new OpenAPI()
                .info(new Info()
                        .title("Shopflow Backend API")
                        .version(apiVersion)
                        .description(
                                "REST API for the Shopflow sales and inventory management system. "
                                        + "Includes catalog, order, payment, delivery, inventory, "
                                        + "receiving, customer returns, dashboard and access control.")
                        .contact(new Contact()
                                .name("ShopFlow Team")
                                .email("tuan@hoangtuan.dev"))
                        .license(new License()
                                .name("MIT License")
                                .url("https://opensource.org/licenses/MIT")));
    }
}
