spring:
  application:
    name: shopflow-backend
  profiles:
    default: dev
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: shopflow
  flyway:
    enabled: true
    schemas: shopflow
    default-schema: shopflow

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

shopflow:
  openapi:
    version: 0.0.1-SNAPSHOT

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
