spring:
  application:
    name: shopflow-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shopflow}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    schemas: shopflow
    default-schema: shopflow

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

shopflow:
  openapi:
    version: 0.0.1-SNAPSHOT
